frontend:
  enabled: true
  image:
    repository: kubespheredev/[[ .Name ]]-frontend
    tag: latest
    pullPolicy: IfNotPresent

backend:
  enabled: true
  image:
    repository: kubespheredev/[[ .Name ]]-api
    tag: latest
    pullPolicy: IfNotPresent
