apiVersion: extensions.kubesphere.io/v1alpha1
kind: JSBundle
metadata:
  name: [[ .Name ]]
spec:
  rawFrom:
    url: http://{{ include "frontend.fullname" . }}.{{ .Release.Namespace }}.svc/dist/index.js
status:
  state: Available
  link: /dist/[[ .Name ]]/index.js
